export let ColumnData = [
  {
    mode: 'F',
    headerName: 'Group cost center',
    field: 'k.0',
    type: ['string'],
    values: [],
    editable: true,
    cellEditor: 'editComp',
    cellEditorParams: {
      values: [
        { id: 1, name: '200001 - General Management' },
        { id: 2, name: '200002 - Management' },
        { id: 3, name: '200003 - DataCenter' },
        { id: 4, name: '200009 - Location Hamburg' }
      ]
    },
    dependentOf: 'COSTUNITLINK',
    dependentValues: {
      '200009 - Location Hamburg': '200009 - Location Hamburg',
      '03 Request Fulfilment': '-'
    },
    aggFunc: null,
    rowGroup: false,
    pinned: 'left',
    sort: 'asc',
    sortedAt: -1
  },
  {
    mode: 'F',
    headerName: 'Cost unit',
    field: 'k.1',
    type: ['string', 'selectionvalues', 'required'],
    values: [
      '0001-DesktopPC',
      '01 Change Management',
      '01 Event Management',
      '01 Service Catalogue Management',
      '01 Service Evaluation',
      '01 Service Portfolio Management'
    ],
    dependentOf: null,
    dependentValues: {},
    aggFunc: null,
    rowGroup: false,
    editable: true,
    pinned: 'left',
    sort: 'asc',
    sortedAt: 0
  },
  {
    mode: 'F',
    headerName: 'Cost type',

    field: 'k.2',
    type: ['string', 'selectionvalues', 'required'],
    values: [
      '0001 - Personal',
      '0002 - Reise',
      '0003 - ILV-Raum',
      '0004 - ILV-HR'
    ],
    dependentOf: null,
    dependentValues: {},
    aggFunc: null,
    rowGroup: false,
    editable: true,
    pinned: 'left',
    sort: 'asc',
    sortedAt: 1
  },
  {
    mode: 'F',
    headerName: 'Cost center ID',
    field: 'k.3',
    type: ['string', 'selectionvalues', 'required'],
    values: [
      '*-Kostenstelle',
      '200001 - General Management',
      '200002 - Management',
      '200003 - DataCenter'
    ],
    dependentOf: null,
    dependentValues: {},
    aggFunc: null,
    rowGroup: false,
    editable: true,
    pinned: 'left',
    sort: 'asc',
    sortedAt: 2
  },
  {
    mode: 'F',
    headerName: 'Line item currency',
    field: 'k.4',
    type: ['string', 'selectionvalues', 'required'],
    values: ['EUR', 'GBP', 'USD'],
    dependentOf: null,
    dependentValues: {},
    aggFunc: null,
    rowGroup: false,
    editable: false,
    pinned: 'left',
    sort: 'asc',
    sortedAt: 3,
    width: 100
  },
  {
    mode: 'G',
    headerName: 'Amount (in EUR) 2011',
    children: [
      // {
      //   mode: 'T',
      //   headerName: 'Total',
      //   field: 'total_2011',
      //   type: ['number', 'float'],
      //   values: [
      //     'AMOUNT_201101',
      //     'AMOUNT_201102',
      //     'AMOUNT_201103',
      //     'AMOUNT_201104'
      //   ],
      //   // aggFunc: 'sum',
      //   editable: true
      // },
      {
        mode: 'F',
        headerName: '(Count)_Amount (in EUR) 01/2011',
        field: 'f.0',
        filter: 'partialMatchFilter',

        type: ['afBigNumber', 'number', 'float'],
        values: [],
        dependentOf: null,
        dependentValues: {},
        rowGroup: false,
        editable: true,
        pinned: null,
        sort: null,
        sortedAt: 0
      },
      {
        mode: 'F',
        headerName: '(Avg)_Amount (in EUR) 02/2011',
        field: 'f.1',

        menuTabs: ['filterMenuTab'],
        filter: 'agNumberColumnFilter',
        type: ['afBigNumber', 'number', 'float'],
        values: [],
        dependentOf: null,
        dependentValues: {},
        rowGroup: false,
        editable: true,
        pinned: null,
        sort: null,
        sortedAt: 0
      },
      {
        mode: 'F',
        headerName: '(Sum)_Amount (in EUR) 03/2011',
        field: 'f.2',
        type: ['afBigNumber', 'number', 'float'],
        values: [],
        dependentOf: null,
        dependentValues: {},
        rowGroup: false,
        editable: true,
        pinned: null,
        sort: null,
        sortedAt: 0
      },
      {
        mode: 'F',
        headerName: '(Min)_Amount (in EUR) 04/2011',
        field: 'f.3',
        type: ['afBigNumber', 'number', 'float'],
        values: [],
        dependentOf: null,
        dependentValues: {},
        rowGroup: false,
        editable: true,
        pinned: null,
        sort: null,
        sortedAt: 0
      },
      {
        mode: 'F',
        headerName: '(Max)_Amount (in EUR) 05/2011',
        field: 'f.4',
        type: ['afBigNumber', 'number', 'float'],
        values: [],
        dependentOf: null,
        dependentValues: {},
        rowGroup: false,
        editable: true,
        pinned: null,
        sort: null,
        sortedAt: 0
      },
      {
        mode: 'F',
        headerName: 'Amount (in EUR) 06/2011',
        field: 'AMOUNT_201106',
        type: ['number', 'float'],
        values: [],
        dependentOf: null,
        dependentValues: {},
        rowGroup: false,
        editable: true,
        pinned: null,
        sort: null,
        sortedAt: 0
      },
      {
        mode: 'F',
        headerName: 'Amount (in EUR) 07/2011',
        field: 'AMOUNT_201107',
        type: ['number', 'float'],
        values: [],
        dependentOf: null,
        dependentValues: {},
        rowGroup: false,
        editable: true,
        pinned: null,
        sort: null,
        sortedAt: 0
      },
      {
        mode: 'F',
        headerName: 'Amount (in EUR) 08/2011',
        field: 'AMOUNT_201108',
        type: ['number', 'float'],
        values: [],
        dependentOf: null,
        dependentValues: {},
        rowGroup: false,
        editable: true,
        pinned: null,
        sort: null,
        sortedAt: 0
      },
      {
        mode: 'F',
        headerName: 'Amount (in EUR) 09/2011',
        field: 'AMOUNT_201109',
        type: ['number', 'float'],
        values: [],
        dependentOf: null,
        dependentValues: {},
        rowGroup: false,
        editable: true,
        pinned: null,
        sort: null,
        sortedAt: 0
      },
      {
        mode: 'F',
        headerName: 'Amount (in EUR) 10/2011',
        field: 'AMOUNT_201110',
        type: ['number', 'float'],
        values: [],
        dependentOf: null,
        dependentValues: {},
        rowGroup: false,
        editable: true,
        pinned: null,
        sort: null,
        sortedAt: 0
      },
      {
        mode: 'F',
        headerName: 'Amount (in EUR) 11/2011',
        field: 'AMOUNT_201111',
        type: ['number', 'float'],
        values: [],
        dependentOf: null,
        dependentValues: {},
        rowGroup: false,
        editable: true,
        pinned: null,
        sort: null,
        sortedAt: 0
      },
      {
        mode: 'F',
        headerName: 'Amount (in EUR) 12/2011',
        field: 'AMOUNT_201112',
        type: ['number', 'float'],
        values: [],
        dependentOf: null,
        dependentValues: {},
        rowGroup: false,
        editable: true,
        pinned: null,
        sort: null,
        sortedAt: 0
      }
    ]
  },
  {
    mode: 'F',
    headerName: 'Test-Targetvalue (in EUR)',
    field: 'TARGET',
    type: ['number', 'float'],
    values: [],
    dependentOf: null,
    dependentValues: {},
    // aggFunc: 'sum',
    rowGroup: false,
    editable: false,
    pinned: null,
    sort: null,
    sortedAt: 0
  },
  {
    mode: 'F',
    headerName: 'Test-Share',
    field: 'SOLUTION',
    type: ['number', 'float'],
    values: [],
    dependentOf: null,
    dependentValues: {},
    // aggFunc: 'sum',
    rowGroup: false,
    editable: false,
    pinned: null,
    sort: null,
    sortedAt: 0
  }
];
